# Generated by Django 6.0.6 on 2026-06-26 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField()),
                ('weight', models.CharField(default='1 kg', max_length=50)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('payment', models.CharField(choices=[('naqd', 'Naqd pul'), ('karta', 'Bank kartasi'), ('click', 'Click / Payme')], default='naqd', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('delivered', 'Yetkazildi'), ('canceled', 'Bekor qilindi')], default='new', max_length=20)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='main.customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.PositiveIntegerField()),
                ('line_total', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='main.product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
